name: github pages

on:
  push:
    branches:
      - master
      - feat/upgrade-react-components

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # build current site
      - name: Current site
      - working-directory: ./
        - run: ls
        - run: npm ci
        - run: npm run build

      # build new site
      - name: New site
      - working-directory: ./new
        - run: ls
  #      - uses: borales/actions-yarn@v2.0.0
        - run: npm ci
        - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.saucedemo.com
