# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # New Site steps
    - name: New site - Install dependencies
      working-directory: ./new
      run: yarn

    - name: New site - Run Unit Tests and generate coverage report
      working-directory: ./new
      run: yarn test.coverage

    - name: New site - Build and E2E test the new site
      working-directory: ./new
      run: |
        yarn start
        yarn test.e2e.sauce.us
